# generated by datamodel-codegen:
#   filename:  workdir/platform_acme_co_v1alpha1_accountscaffold.yaml
#   timestamp: 2024-10-08T09:14:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionSelector(BaseModel):
    matchLabels: Dict[str, str]


class CompositionUpdatePolicy(Enum):
    Automatic = 'Automatic'
    Manual = 'Manual'


class Parameters(BaseModel):
    name: str
    """
    The name of the account to be scaffolded.

    """


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str


class WriteConnectionSecretToRef(BaseModel):
    name: str


class Spec(BaseModel):
    compositionRef: Optional[CompositionRef] = None
    compositionRevisionRef: Optional[CompositionRevisionRef] = None
    compositionSelector: Optional[CompositionSelector] = None
    compositionUpdatePolicy: Optional[CompositionUpdatePolicy] = 'Automatic'
    parameters: Parameters
    """
    The parameters indicating how this account should
    be configured.

    """
    resourceRef: Optional[ResourceRef] = None
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: Optional[str] = None
    reason: str
    status: str
    type: str


class ConnectionDetails(BaseModel):
    lastPublishedTime: Optional[AwareDatetime] = None


class Status(BaseModel):
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    connectionDetails: Optional[ConnectionDetails] = None


class AccountScaffold(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Optional[Status] = None


class Field(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[AccountScaffold]
    """
    List of accountscaffolds. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """